name: my_news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  equatable: ^2.0.8
  dio: ^5.9.0
  retrofit: ^4.9.2
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  logger: ^2.6.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.7.1
  hive_ce_generator: ^1.9.5
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  

flutter:
  uses-material-design: true
